### ISSUE TITLE
open notebook leads to empty browser window

### ISSUE THREAD

**Issue by sharnett** [maxroberts/Notebook-Buddy#3]
After I choose "Browse" and select a notebook, I click "Open" and it opens up a new empty window in Chrome. I think it should open up the notebook.

**Comment by maxroberts** [comment]
It's also supposed to open a terminal, does that not happen? If it did
open, maybe there's an error message there?

**Comment by sharnett** [comment]
Aha, there it is. The terminal didn't come to the front. I don't have any jupyter stuff installed into the system python, I always use an anaconda environment so this might not work for me.

**Comment by maxroberts** [comment]
It would be cool to integrate that flexibility though, like you provide a
python path or something (optionally). Any ideas on that?

**Comment by sharnett** [comment]
Yeah, take a look at what the ~/miniconda/bin/activate script does. I think it changes the python path and some other environment variables. Maybe you could just run that.

**Comment by maxroberts** [comment]
Ok, I tried to add this functionality. The drop-down should have an option
for anaconda, but you can modify the command to whatever you need (I
think). Give it a try when you're bored.
